### ISSUE TITLE
Same card - different pack linking

### ISSUE THREAD

**Issue by iwittenberg** [NetrunnerDB/netrunner-cards-json#279]
Use case:  Decks on netrunnerdb are starting to reference cards from Core 2.0 which contains cards from across cycles and obviously has different card numbers from the previous Core set.  It'd be great to have a way to mark cards as duplicate so that decklists can list any set that or pack that a card could have come from.  In conjunction with some extra work on netrunnerdb or an external browser extension/application, it'd be possible to add "with the cards I have, can I build this and if so, where can I find those cards in my inventory, if not what packs do I need" as opposed to "only show me decks for the cards I own"

**Comment by plural** [comment]
this is actually in scope for NRDB v2.  Basically, we are going to separate out the notion of a Card (basically, unique by Title) from a Printing (a specific instance of a card in a particular pack/set).

I'm going to leave this open to see if we are going to address it here in the JSON data or in the NRDB repo only.

**Comment by plural** [comment]
I'm going to close this issue out now that we have a card format and a printing format (the different pack referenced in the original issue).

NRDB shows these printings now and NRDB v2 will make them EVEN BETTER.
