### ISSUE TITLE
Indicator for incomplete packs (cores)

### ISSUE THREAD

**Issue by danj3000** [NetrunnerDB/netrunner-cards-json#367]
Is there a way to indicate that a pack does not hold 3x each card e.g. core set, and is therefore suitable for multiples.

This spring out of my desire to drive the ANR deckbuilder app options from data rather than having to hard code which packs are cores, and therefore may have 1,2,3 copies.

**Comment by gereons** [comment]
We have the "quantity" property for every card, if any of those is less than 3 then the pack would be suitable for multiples.

**Comment by danj3000** [comment]
Reign and reverie is the odd one out in that approach - 1x cards like DJ Fenris, lady liberty
A flag on the pack would be definitive

**Comment by gereons** [comment]
True, I forgot. So the check to do would be `quantity < deck_limit` instead.
