### ISSUE TITLE
Code/Position for Sure Gamble/Hedge Fund in System Gateway

### ISSUE THREAD

**Issue by gereons** [NetrunnerDB/netrunner-cards-json#560]
Do we know these codes already? If so, it would be great to add them early, so that we can complete the mapping table for conversion from old decks to new gateway/update21-based decks.

**Comment by NoahTheDuke** [comment]
Mapping table?

**Comment by gereons** [comment]
Yeah, like the one in https://github.com/NetrunnerDB/netrunnerdb/blob/d62e3a3df31e628fe28805d8006825a274a7692e/web/js/nrdb.js#L756

**Comment by francescopellegrini** [comment]
Fixed by #563?

**Comment by gereons** [comment]
Indeed. Thanks!
