### ISSUE TITLE
Typo in Manegarm Skunkworks wording?

### ISSUE THREAD

**Issue by francescopellegrini** [NetrunnerDB/netrunner-cards-json#565]
![Manegarm Skunkworks](https://netrunnerdb.com/card_image/large/30042.jpg)

https://github.com/NetrunnerDB/netrunner-cards-json/blob/4bb5e6384a86cdeaf98e32d97e534351527d97b3/pack/sg.json#L598

The wording differs from the card shown by Nisei: is this a bug or did I misinterpreted the [recent rules change](https://nisei.net/blog/susg-rules-changes/) on the structure of the run?

**Comment by NoahTheDuke** [comment]
Thanks for the report! We'll get a fix up soon.

**Comment by gereons** [comment]
This was fixed in #569, afaict.
