### ISSUE TITLE
Security Leak not addable to decks

### ISSUE THREAD

**Issue by deathByLiche** [NetrunnerDB/netrunner-cards-json#566]
Security Leak shows up as a card in the Terminal Directive Campaign cards set, but it currently doesn't show up when searching for it to add to a deck, whereas the other campaign cards do.

**Comment by gereons** [comment]
Just a guess: is this because all Currents are banned? Anyway, the issue is more likely better suited for https://github.com/NetrunnerDB/netrunnerdb/issues since the raw data here looks fine.

**Comment by deathByLiche** [comment]
Ah, looks like you are right, as it is happening on the corp side with Net Watchlist as well. I'll close this issue and open one in the other repo.
