### ISSUE TITLE
Mirrormorph Rulings Out of Date

### ISSUE THREAD

**Issue by codaOnGithub** [NetrunnerDB/netrunner-cards-json#583]
Mirrormorph currently has the Nisei Downfall Release Notes ruling underneath it stating that you can take an action after using your third click on a Terminal operation. That was changed in the 1.3 Comprehensive Rules update released on 7/20/2019, and now you cannot take any action outside of your action phase, including the one Mirrormorph tries to grant you.

**Comment by plural** [comment]
so rulings aren't actually handled in the JSON for this repo - they live in NRDB's database, unfortunately.  I'll let the rules folks know, though.
