### ISSUE TITLE
Dashes versus underscores

### ISSUE THREAD

**Issue by NoahTheDuke** [NetrunnerDB/netrunner-cards-json#619]
With the new data format (cards and printings and subtypes etc), the ids use underscores as that matches how identifiers are written in Ruby. However, the pre-existing ids (pack_id, etc) use dashes. Should we unify under one or another?

**Comment by plural** [comment]
underscores aren't just for Ruby, though.  JS also can't use ids with - in them.

I think underscores are a-ok, personally.
