### ISSUE TITLE
Do the v2 printing cards need text fields?

### ISSUE THREAD

**Issue by plural** [NetrunnerDB/netrunner-cards-json#669]
We currently have printed_text and stripped_printed_text, but do we need it?  We don't want printings to have different text and have already taken an "update everything at once" approach when making text and rules changes.

Do we need these fields at all in v2?

**Comment by NoahTheDuke** [comment]
It's nice to say "what is physically printed in the card?" I don't think we do anything with it but we could.

**Comment by infinitenutshell** [comment]
If NRDB2 is going to have better support for cards with multiple printings anyway, then yeah we might as well be able to search the actual words that appear on each physical version of the card.

**Comment by plural** [comment]
I think we wanna think through the implications of this carefully.  For v2 We currently have a card that is the authoritative text for, um, a card.  a printing has the bits that are different for that particular instance.  Illustrator, flavor text, position in a card set, etc.

We currently have tests ensuring that the text and printed text fields match so that we aren't accidentally causing bugs.  That's what caused this question in the first place.

If we want to have literal printed text, do we leave it alone when rules gives us new text updates because it isn't what was printed?  What's the difference between printing 1 of a card and printing 2 once a rules / text update happens?  They are both historical artifacts, but .... useless?

**Comment by infinitenutshell** [comment]
My intuition is that official text should be a field per-card, but printed text should be a field per-printing. If there have been no changes from the rules team since the most recent printing, those two fields will contain the same data, but only the official text would be updated going forward.

We don't necessarily have to do any of this (it doesn't look like Scryfall supports historical text at all), but if we want to, that's how I would expect it to work.

**Comment by infinitenutshell** [comment]
So I guess to answer the question, you need "printed text" fields if and only if you want to actually capture printed text, which is a historical artifact but has little importance to current gameplay, in the database.

**Comment by NoahTheDuke** [comment]
I agree with @infinitenutshell

**Comment by plural** [comment]
hmmm, ok.  I don't know if we want to enable search or anything for exact text on printings, but we can discuss more.

If we do this, i'll need to drop the tests that enforce that printings and cards match, but that's just deleting code.  :)
