### ISSUE TITLE
Costs in System Gateway are not always bold

### ISSUE THREAD

**Issue by SpencerDub** [NetrunnerDB/netrunner-cards-json#708]
I have been trying to fix this over on my fork, but trying to bring my repo up-to-date with this one has introduced weirdnesses and unnecessary commit messages and I worry about muddying this repo.

Anyway, numerical or symbolic costs in System Gateway (like icebreaker ability costs) are not wrapped in `<strong>` tags, and they should be.

**Comment by francescopellegrini** [comment]
I couldn't find any SG card missing `<strong>` tags: which cards are you referring to?

**Comment by plural** [comment]
I also took a look and didn't see any missing bold for System Gateway, @SpencerDub .

**Comment by SpencerDub** [comment]
As far as I can tell, it is on every card in System Gateway and System Update 2021 that has a paid ability cost that does not contain alphabetical characters, plus some extras.

In these sets, these costs are written like this:

```
1[credit]: Break 1 subroutine.
```

or

```
[click], [trash]: Gain 3[credit].
```

instead of:

```
<strong>1[credit]:</strong> Break 1 subroutine.
```

or

```
[click], [trash]<strong>:</strong> Gain 3[credit].
```

The following cards are affected:

## System Gateway
- [Buzzsaw](https://netrunnerdb.com/en/card/30005)
- [Cleaver](https://netrunnerdb.com/en/card/30006)
- [Fermenter](https://netrunnerdb.com/en/card/30007) (colon)
- [Pennyshaver](https://netrunnerdb.com/en/card/30014) (colon)
- [Carmen](https://netrunnerdb.com/en/card/30015)
- [Marjanah](https://netrunnerdb.com/en/card/30016)
- [Red Team](https://netrunnerdb.com/en/card/30018) (colon)
- [Conduit](https://netrunnerdb.com/en/card/30024) (colon)
- [Echelon](https://netrunnerdb.com/en/card/30025)
- [Unity](https://netrunnerdb.com/en/card/30026)
- [Telework Contract](https://netrunnerdb.com/en/card/30027) (colon)
- [Mayfly](https://netrunnerdb.com/en/card/30032)
- [Smartware Distributor](https://netrunnerdb.com/en/card/30033) (colon)
- [Regolith Mining License](https://netrunnerdb.com/en/card/30071) (colon)

## System Update 2021
- [Quetzal](https://netrunnerdb.com/en/card/31001)
- [Corroder](https://netrunnerdb.com/en/card/31006)
- [Mimic](https://netrunnerdb.com/en/card/31008)
- [Liberated Account](https://netrunnerdb.com/en/card/31010) (colon)
- [Abagnale](https://netrunnerdb.com/en/card/31021)
- [Femme Fatale](https://netrunnerdb.com/en/card/31022)
- [Ayla "Bios" Rahim](https://netrunnerdb.com/en/card/31025) (colon)
- [Atman](https://netrunnerdb.com/en/card/31030)
- [Chameleon](https://netrunnerdb.com/en/card/31031)
- [Gordian Blade](https://netrunnerdb.com/en/card/31033)
- [Professional Contacts](https://netrunnerdb.com/en/card/31036)
- [Corporate Troubleshooter](https://netrunnerdb.com/en/card/31049)
- [Ronin](https://netrunnerdb.com/en/card/31053)
- [Reversed Accounts](https://netrunnerdb.com/en/card/31064) (colon)

## Downfall
- [Flip Switch](https://netrunnerdb.com/en/card/26013) (colons)
- ["Baklan" Bochkin](https://netrunnerdb.com/en/card/26017) (colon)
- [Pelangi](https://netrunnerdb.com/en/card/26025) (colon)
- [The Artist](https://netrunnerdb.com/en/card/26027) (colons)
- [Calvin B4L3Y](https://netrunnerdb.com/en/card/26033) (colon)
- [Nanoetching Matrix](https://netrunnerdb.com/en/card/26034) (colon)
- [Cold Site Server](https://netrunnerdb.com/en/card/26038) (colon)
- [Hyoubu Institute](https://netrunnerdb.com/en/card/26039) (colon)
- [Remastered Edition](https://netrunnerdb.com/en/card/26047) (colon)
- [Roughneck Repair Squad](https://netrunnerdb.com/en/card/26057) (colon)

## Uprising
- [Gachapon](https://netrunnerdb.com/en/card/26069) (colon)
- [Boomerang](https://netrunnerdb.com/en/card/26075) (colon)
- [Prognostic Q-Loop](https://netrunnerdb.com/en/card/26077)
- [Simulchip](https://netrunnerdb.com/en/card/26085) (colon)
- [Self-modifying Code](https://netrunnerdb.com/en/card/26090) (colon)
- [Bass CH1R180G4](https://netrunnerdb.com/en/card/26098) (colon)
- [F2P](https://netrunnerdb.com/en/card/26115)
- [Earth Station](https://netrunnerdb.com/en/card/26120) (colon)

## Points of Comparison

Compare the lack of bold in the above cards to these examples:
- [Abaasy](https://netrunnerdb.com/en/card/33070)
- [Hush](https://netrunnerdb.com/en/card/33071)
- [Euler](https://netrunnerdb.com/en/card/26087)
- [Lustig](https://netrunnerdb.com/en/card/13007)
- [Stargate](https://netrunnerdb.com/en/card/26004)

## Style Reference

Looking back over internal NSG discussions in the Rules public channel (June 6, 2022), Jamie has confirmed that this is the Rules Team's style:

- Each individual non-glyph component of a cost ("suffer 1 core damage", "hosted virus counter") is bold.
- The colon after a cost is bold.
- The commas between cost components are not bold.
- Glyphs are not bold.

Here in the JSON, for something like "1[credit]: Break 1 subroutine", where there's no visual distinction to marking the glyph as bold, I would argue it's acceptable to just wrap everything in a single set of `<strong>` tags, rather than `<strong>1</strong>[credit]<strong>:</strong>`, just for ease of reading.
