### ISSUE TITLE
Duplicate `"designed_by":` items in JSON

### ISSUE THREAD

**Issue by sboosali** [NetrunnerDB/netrunner-cards-json#793]
e.g. `akhet.json` has:

    "designed_by": "null_signal_games",
    "designed_by": "null_signal_games",
    "designed_by": "null_signal_games",

https://github.com/NetrunnerDB/netrunner-cards-json/blob/main/v2/cards/akhet.json

I can work on it if you think it's a "newcomer" issue, to start contributing.

**Comment by plural** [comment]
woah, i missed this a long time ago.  Sorry about that.  We sorted this accidentally in the meantime while tidying some things up.
